// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8PvRFm4bC4hciUS74nikfS7NU1f4koB8',
    appId: '1:530473948047:web:0e1c886a6485d77e7db1fa',
    messagingSenderId: '530473948047',
    projectId: 'my-notes-595a1',
    authDomain: 'my-notes-595a1.firebaseapp.com',
    storageBucket: 'my-notes-595a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_HWjPL8IPGOXz5xefcLx25hZVy19N3I0',
    appId: '1:530473948047:android:13931716431940817db1fa',
    messagingSenderId: '530473948047',
    projectId: 'my-notes-595a1',
    storageBucket: 'my-notes-595a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtf3AnoD9-OkcuzPNitC6jf51U5EeZK7M',
    appId: '1:530473948047:ios:1e659d3d86c4578e7db1fa',
    messagingSenderId: '530473948047',
    projectId: 'my-notes-595a1',
    storageBucket: 'my-notes-595a1.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );
}
